web_pra/web15/models/__init__.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.ext.declarative import declared_attr

db = SQLAlchemy()


class Model(db.Model):
    __abstract__ = True

    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower() + 's'

    @classmethod
    def add(cls, m):
        db.session.add(m)
        db.session.commit()

    @classmethod
    def find_by(cls, **kwargs):
        return cls.query.filter_by(**kwargs).first()

    @classmethod
    def find_all(cls, **kwargs):
        return cls.query.filter_by(**kwargs).all()

web_pra/web15/models/message.py
from models import db, Model
import time
from utils import current_time


class Message(Model):

    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String)
    author = db.Column(db.String)
    created_time = db.Column(db.Integer)
    deleted = db.Column(db.Boolean)

    def __init__(self, form: dict):
        self.content = form.get('content', '')
        self.author = form.get('author', '')
        self.created_time = int(time.time())
        self.deleted = False

    @classmethod
    def delete(cls, id):
        m = cls.query.get(id)
        m.deleted = True
        db.session.commit()
        return m

    @classmethod
    def update(cls, id, content):
        m = cls.query.get(id)
        m.content = content
        db.session.commit()
        return m

    def current_time(self):
        return current_time(self.created_time)

web_pra/web15/models/user.py
from models import db, Model
from utils import sha256


class User(Model):

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20))
    password = db.Column(db.String(20))

    def __init__(self, form: dict):
        self.username = form.get('username', '')
        self.password = form.get('password', '')

    def salted_password(self, password, salt='abcdefg'):
        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        return hash2

    @classmethod
    def register(cls, form: dict):
        name = form.get('username', '')
        pwd = form.get('password', '')
        if len(name) > 2 and cls.find_by(username=name) is None:
            # 说明未注册过
            u = cls(form)
            u.password = u.salted_password(pwd)
            cls.add(u)
            return u
        else:
            return None

    @classmethod
    def validate_login(cls, form: dict):
        u = cls(form)
        # 这里注意查询的时候需要使用 .first() 可以保证当没有查询到的时候可以返回 None
        user = cls.find_by(username=u.username)
        if user is not None and user.password == u.salted_password(u.password):
            return user
        return None

web_pra/web15/app.py
import os
from flask import Flask
from models import db
from models.user import User
from models.message import Message


from routes.index import index_bp as index_routes
from routes.message import message_bp as message_routes

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////' + os.path.join(app.root_path, 'db', 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

app.secret_key = 'limboer'
db.init_app(app)

app.register_blueprint(index_routes)
app.register_blueprint(message_routes, url_prefix='/message')


if __name__ == '__main__':
    config = dict(
        debug=True,
        host='0.0.0.0',
        port=2000,
    )
    app.run(**config)

web_pra/web15/routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
)
from models.user import User

index_bp = Blueprint('index', __name__)


def current_user():
    """
    从 session 中找到 user_id 字段, 找不到返回 -1
    session 已经是加密的, 通过前面的 app.secret_key 加密
    返回 user, 没有为 None
    """
    uid = session.get('user_id', -1)
    u = User.query.get(uid)
    return u


@index_bp.route('/')
def index():
    """
    主页, 包括显示登录和注册
    """
    u = current_user()
    template = render_template('index.html', user=u)
    # 如果要写入 cookie, 必须使用 make_response 函数构造一个 response, 再对该响应添加 cookie
    res = make_response(template)
    res.set_cookie('cookie_name', 'limboer')
    return res


@index_bp.route('/register', methods=['POST'])
def register():
    form = request.form
    u  = User.register(form)
    return redirect(url_for('index.index'))


@index_bp.route('/login', methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('index.index'))
    else:
        # 写入 session
        session['user_id'] = u.id
        return redirect(url_for('index.profile'))


@index_bp.route('/logout', methods=['GET'])
def logout():
    # 退出登录即为清除 session
    session.pop('user_id')
    return redirect(url_for('index.index'))


@index_bp.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    else:
        return render_template('profile.html', user=u)

web_pra/web15/routes/message.py
from models.message import Message
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

message_bp = Blueprint('message', __name__)


@message_bp.route('/')
def index():
    messages = Message.query.all()
    return render_template('message.html', messages=messages)


@message_bp.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Message(form)
    Message.add(m)
    return redirect(url_for('message.index'))


@message_bp.route('/delete/<int:message_id>', methods=['GET'])
def delete(message_id):
    m = Message.delete(message_id)
    return redirect(url_for('message.index'))

web_pra/web15/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
</head>
<body>
    <h1>Hello {{ user.username if user != None else '游客' }}</h1>
    <h2>
        <a href="{{ url_for('index.profile') }}">个人资料页面</a>
    </h2>
    <form method="post" action="{{ url_for('index.register') }}">
        <fieldset>
            <legend>Register</legend>

            <label>username: </label>
            <input name="username" title="enter username">
            <br>

            <label>password: </label>
            <input name="password" title="enter password">
            <br>
            <button type="submit">注册</button>
        </fieldset>
    </form>

    <form method="post" action="{{ url_for('index.login') }}">
        <fieldset>
            <legend>Login</legend>
            <label>username: </label>
            <input name="username" title="enter username">
            <br>

            <label>password: </label>
            <input name="password" title="enter password">
            <br>
            <button type="submit">登录</button>

        </fieldset>
    </form>

    {% if user != None %}
        <form method="GET" action={{ url_for("index.logout") }}>
            <button type="submit">退出登录</button>
        </form>

        <div>
            链接:
            <a href={{ url_for("message.index") }}>留言板</a>
        </div>
    {% endif %}

</body>
</html>

web_pra/web15/templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>留言板</title>
    <link href="//cdn.bootcss.com/bootstrap/4.0.0-alpha.6/css/bootstrap.css" rel="stylesheet">
</head>
<body>

<h1>留言板</h1>
<form method="POST" action={{ url_for('message.add') }}>
    <input class="form-control" type="text" name="content" placeholder="message">
    <input class="form-control" type="text" name="author" placeholder="author">
    <button class="btn btn-primary" type="submit">提交留言</button>
</form>

<div>
    {% for m in messages %}
        <div class="alert alert-success" role="alert">
            {{ m.content }} for {{ m.author }} @ {{ m.current_time() }}
            <a href={{ url_for('message.delete', message_id=m.id) }}>删除评论</a>
        </div>
    {% endfor %}

    <button type="button" class="btn btn-link">
        <a href={{ url_for('index.index') }}>返回主页</a>
    </button>


</div>

</body>
</html>

web_pra/web15/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
    <h1>用户资料页面</h1>
    <div>
        id: {{ user.id }}
    </div>
    <div>
        username: {{ user.username }}
    </div>
    <div>
        password: {{ user.password }}
    </div>

    <h3>
        <a href="{{ url_for('index.index') }}">返回主页</a>
    </h3>
</body>
</html>